### ISSUE TITLE
本地运行，requests无法下载图片

### ISSUE THREAD

**Issue by leven-ls** [qwIvan/microMsg-bot#1]
本地运行的server.py，发现能登陆，能根据关键词搜索到图片，并返回url，但是在requests请求url的过程中断，无返回结果.
另外，直接手写requests去请求响应的图片地址是能成功的

我修改了下代码试着直接输出图片
发现图片压根没下载成功，0 KB。

回复上传图片一直失败，没法截图出来了

**Comment by qwIvan** [comment]
有log吗？

**Comment by qwIvan** [comment]
你是在什么系统上运行？有可能是NamedTemporaryFile的问题。

**Comment by leven-ls** [comment]
win10上运行的，没看到log file之类的，我觉得不是namedtemporayfile的问题，因为我在对应位置尝试拦截了resp输出图片，发现是个0KB的文件

 
我试过在ubuntu 16.04的docker直接运行，但是他要占用80端口，然后我设置启动在另外个端口，但是发现运行出来跳转到了ngix的设置界面

**Comment by qwIvan** [comment]
@leven-ls 整个 docker image 里并没有包含NginX，可能是你端口设置错误或者浏览器有缓存。
试一下 `-p 80:8000` ？

**Comment by leven-ls** [comment]
在ubuntu上调试成功了，是缓存的锅。

个人感觉，交互方式按照 ***.jpg的形式有点太程序化，有空来加点NLP的东西进来根据消息内容，斗图更得劲

**Comment by qwIvan** [comment]
@leven-ls 这种设计主要是为了不影响正常聊天。如果有需要的话，增加选项自定义规则、正则匹配也很简单。至于NLP，就不是稍微改改代码就能加上的了。。

**Comment by leven-ls** [comment]
其实NLP也没那么难，有空我来加点有趣的NLP功能进来

**Comment by qwIvan** [comment]
@leven-ls 可以啊。欢迎增加功能。

**Comment by zitup** [comment]
@leven-ls 所以，新功能呢😂
