### ISSUE TITLE
是否失效了

### ISSUE THREAD

**Issue by leung44** [qwIvan/microMsg-bot#3]
登录测试没用哇

**Comment by qwIvan** [comment]
没用是什么表现

**Comment by leung44** [comment]
> 没用是什么表现

扫码登录之后测试传图没有转表情回复

**Comment by qwIvan** [comment]
@leung44 看log

**Comment by qwIvan** [comment]
默认可以用.jpg后缀触发

**Comment by leung44** [comment]
![image](https://user-images.githubusercontent.com/30283855/48251482-c2aba680-e43c-11e8-8498-c10715696b84.png)

**Comment by qwIvan** [comment]
发文字自动回复表情。懂吗。

**Comment by leung44** [comment]
oh my, got it
